### ISSUE TITLE
Keyboard doesn't reflect changes in pattern names, channel rack plugin names and channel rack volumes

### ISSUE THREAD

**Issue by twentythreeQuestions** [hobyst/flmidi-kompletekontrol#11]
The screen on my komlete kontrol MK2 keyboard doesn't change if I change the volume or the name of the pattern for example.

**Comment by hobyst** [comment]
Patterns aren't meant to show on the screen, so it's obvious nothing will happen if you change the name of a pattern. 

About the volume you mention, the screen is meant to be a mirror of FL Studio's mixer window, just as your keyboard has a MIXER button. Changing anything in the channel rack won't do anything on the screen as it only shows changes in the mixer based on the currently selected track and the surrounding ones. This is the way it is meant to work.
