### ISSUE TITLE
Meters on Mixer not working

### ISSUE THREAD

**Issue by volpi3000** [hobyst/flmidi-kompletekontrol#14]
Hi,
First of all thank you for creating this! I have an issue with Mixer. I installed the script and most of seems to be working fine.If I go to the Mixer Tab, I can change the Fader Levels, but the Meter display on my S61 MK2 is not showing any levels. It is showing the "Mixer Page" though.

 
<img width="499" alt="Capture" src="https://user-images.githubusercontent.com/1008177/104120513-ca767680-5337-11eb-87f8-d86e3580f3b8.PNG">

Thank you and Best regards,

Volpi

**Comment by hobyst** [comment]
Your MIDI settings are correctly set up, so there shouldn't be any problem. Please, try updating to the latest stable release of FL Studio or reinstalling it to see if it works. 
I have seen some people having issues with FL Studio not triggering the action inside their scripts that is used to update peak meters on MIDI devices. However, on my end works just fine.

**Comment by hobyst** [comment]
Closed due to inactivity.
