### ISSUE TITLE
Fl Studio crashin when loading script

### ISSUE THREAD

**Issue by DieserTii** [hobyst/flmidi-kompletekontrol#16]
Hi at first thank you for this great script! You´re like a superhero to me! I really appreciate.

For the latest update of FL I was forced to do a clean installation (20.8.3). Also Iam forced to reconfigurate all my settings.
So, when I try to load your script, FL is bringing up the sandclock and when I click onto the settings window, FL is crashing.

Before the update everything was working fine with your script.

Do you have any suggestions, what I can do?

**Comment by hobyst** [comment]
On the latest FL Studio update (20.8.3) a new bug appeared on the Python interpreter found on FL Studio that pretty much messes up with a lot of MIDI scripts, including mine.

It already got [confirmed](https://forum.image-line.com/viewtopic.php?f=100&t=253503&start=50#p1603523) by Image-Line this was indeed an issue from FL Studio and that would get fixed as soon as possible, so the only thing left is to wait for the patch to be delivered. In the meantime you can set the DAW control surface port (`Komplete Kontrol DAW - 1` or `Komplete Kontrol <SERIES> DAW`, depending on the series your keyboard belongs to) as a Mackie Control Universal device on the MIDI settings of FL Studio so you can at least get transport controls working.

**Comment by DieserTii** [comment]
Okay, thank you for your help. This totally makes sense. I already found out, that after the update FL did not start up, because of your script/the bug from image line.

Thank you!

**Comment by hobyst** [comment]
Re-opening the issue until the update from Image-Line gets released.

**Comment by DieserTii** [comment]
I get back to an older version of FL. Now everything is working fine! Man, I really love your script!

**Comment by hobyst** [comment]
> I get back to an older version of FL. Now everything is working fine! Man, I really love your script!

Thanks!

**Comment by DieserTii** [comment]
Now I tested [a newer Version of FL](https://forum.image-line.com/viewtopic.php?f=100&t=254276&p=1605253#p1605253).
Your script is working fine. But FL is still not good. It crashes while trying to change a script. But once it is choosen, it is working.

**Comment by hobyst** [comment]
Image-Line released the FL Studio build that fixes this issue as stable. Closing the issue.
