### ISSUE TITLE
Panning in Mixerview

### ISSUE THREAD

**Issue by DieserTii** [hobyst/flmidi-kompletekontrol#17]
When in Mixerview on MK2 to see FLs channels. It would be great if it is possible to do some panning additional to moving the fader with the knobs. Switch to panning could be the buttons above the display or the "Shift" button.

**Comment by hobyst** [comment]
Sorry for not answering this before :sweat_smile: . Panning adjustment in the mixer is already supported on the S-Series MK2, you just need to switch between volume and pan adjustment by pressing SHIFT + 4D ENCODER :arrow_up: / :arrow_down:.

**Comment by DieserTii** [comment]
With pressing SHIFT + 4D ENCODER ⬆️ / ⬇️ i can open context menu (right click). But I cannot switch between panning and volume.

**Comment by hobyst** [comment]
> With pressing SHIFT + 4D ENCODER ⬆️ / ⬇️ i can open context menu (right click). But I cannot switch between panning and volume.

Based on that, I think I should explain it further:
The 4D encoder on the Komplete Kontrol keyboards recieves its name from serving both as an encoder/knob/jog wheel and as a 4 directional pad, just like the ones found in videogame console controllers.
* To use it as an encoder, you just twist it.
* To use it as a button, you press it down as in pressing it against the keyboard (perpendicular to the floor of your room).
* To use it as a 4 directional pad, you push the 4D encoder away and closer to you as well as left and right in parallel to the floor of your room as if you were using a joystick from a videogame console controller. [Example here](https://youtu.be/5xvUYH9S-oM?t=77)

When I mean to do SHIFT + 4D ENCODER ⬆️ / ⬇️, is to hold the SHIFT button while using the 4D encoder as a 4-directional pad by pushing it up (away from you) and down (closer to you). It will feel like as if you were trying to strip the encoder away from the keyboard by levering it with your fingers, but you will immediately feel a click from the encoder that will allow you to know exactly how much force you have to do before you start to actually strip it off the keyboard.
