### ISSUE TITLE
Komplete Kontrol Keyboard Mk3 support?

### ISSUE THREAD

**Issue by ededs** [hobyst/flmidi-kompletekontrol#27]
Is it already supported, is it planned to be supported or is there any way ro use the new mk3 edition keyboard with fl studio?

**Comment by hobyst** [comment]
Going by what is written in the [official specifications page](https://www.native-instruments.com/en/products/komplete/keyboards/kontrol-s49-s61-s88/specifications), Native Instruments will officially support the deep integration of Komplete Kontrol MK3 keyboards with FL Studio.
